

FROM ubuntu:TODO


# TODO 
#DISTRIB_ID=Ubuntu
#DISTRIB_RELEASE=16.04
#DISTRIB_CODENAME=xenial
#DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

# 7.0.5 的依赖
# 不要 7.1的!!!!

# COPY seafile.init_data.2.1.tar.gz   /
# pre-require

ADD sources.list  /etc/apt/
RUN apt update \
  && apt install -y ....TODO


# TODO 替换为 
## 安装依赖
    #....
## 安装seafile
    # /seafile/目录下
############
###################
##############

